### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by karakatsanism** [tuteken/Keypirinha-Plugin-Pinboard#1]
Hello and this is a great idea... I am trying to get it to work in keypirinha but it does not get recognized (installed live packages folder). Am I missing something?

**Comment by tuteken** [comment]
Did you create the configuration file with your Pinboard API key in it?  Live package folder should work, although I use mine as an assembled package.

**Comment by karakatsanism** [comment]
I copied the pinboard API key and paste it in the .ini file. I suppose this is not the proper way? thanks for the reply anyway :)

**Comment by tuteken** [comment]
Try this package (attached).  Rename the file from Pinboard.zip to inboard.keypirinha-package, and place it in "<Keypirinha Installation Directory>\default\Packages".  Be sure to remove the files from the "Live" package folder.

If that doesn't work, could you attach the Keypirinha.log file to this thread?  It might be helpful.

[Pinboard.zip](https://github.com/tuteken/Keypirinha-Plugin-Pinboard/files/620495/Pinboard.zip)

**Comment by karakatsanism** [comment]
Hello and thanks for the help and your great plugin! I've managed to set it up properly... :)

**Comment by tuteken** [comment]
Glad to you hear you managed to get it working.  I hope you find it useful.
