### ISSUE TITLE
Ability to assign a shortcut key for Pinboard search

### ISSUE THREAD

**Issue by karakatsanism** [tuteken/Keypirinha-Plugin-Pinboard#2]
Hello and again thanks for your great plugin. Is there a chance to assign a keyword for searching in pinboard? the idea is to keep pinboard results out of the general results unless I specifically choose to call them. Thanks again.

**Comment by tuteken** [comment]
Hello, the latest version of the plugin implements the requested functionality leveraging the Keypirinha standard term of "always_suggest".  The new default behaviour is to keep the Pinboard bookmarks out of the general search results.

**Comment by karakatsanism** [comment]
You are great! Thanks a lot!
