### ISSUE TITLE
Minor improvements

### ISSUE THREAD

**Issue by polyvertex** [tuteken/Keypirinha-Plugin-Pinboard#3]
Hi and thanks for your plugin!

If I may, I've noticed a couple of minor things in the code that may improve your plugin:

* I don't know how Pinboard's API work but it seems you have unintentionally hard-coded your own API token into the code (member `Pinboard.api_token`)
* When dealing with network, please do it via the [keypirinha_net](http://keypirinha.com/api/module-net.html) module. By doing so, your plugin complies to user's network config at **both** Keypirinha and system levels (i.e. see `[network]` section in KP's config file). See the documentation of the [keypirinha_net.build_urllib_opener](http://keypirinha.com/api/module-net.html#keypirinha_net.build_urllib_opener) function for more info. I understand you'll have to write the cache file by yourself then but it should be no trouble!

Also, would you mind if I reference both of your plugins [here](http://keypirinha.com/contributions.html) (i.e. this one and `Ditto`)?

**Comment by tuteken** [comment]
Hi,

Thank you for the feedback.  I most definitely hard coded my personal API key in the plugin (I have since removed it and reset my key).  I took your suggestion and switched to keypirinha_net for the web request.

I wouldn't mind at all if you linked to my plugins.

**Comment by polyvertex** [comment]
You're [live](http://keypirinha.com/contributions.html#tuteken-ditto), thanks!
